# Read from Render's Environment Variables, default to Aiven MySQL local strings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://YOUR_AIVEN_HOST:YOUR_PORT/YOUR_DB_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:YOUR_AIVEN_USER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YOUR_AIVEN_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Force the MySQL 8 Dialect so Hibernate maps data types correctly
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Critical for Render port tracking
server.port=${PORT:8080}